#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/test_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: test
#    password: test123
logging:
  level:
    com.employee.*: DEBUG